In [1]:
include("../src/main.jl");

## Construction of the system

In [2]:
# Define ring of parameters
A, (k1, k2, k3, k4, k5, k6, k7, k8, k9, k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k30, k31, c1, c2, c3, c4, c5) =
    polynomial_ring(QQ, ["k1", "k2", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10", "k11", "k12", "k13", "k14", "k15", "k16", "k17", "k18", "k19", "k20", "k21", "k22", "k23", "k24", "k25", "k26", "k27", "k28", "k29", "k30", "k31", "c1", "c2", "c3", "c4", "c5"]);

# Define ring of parameterized polynomials
B, (x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19) = polynomial_ring(A, ["x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18", "x19"]);

# Define the square(!) system of steady state equations and conservation laws
steadyStateEqs = [
    -k1 * x1 + k2 * x2, # x1
    k1 * x1 - (k2 + k26) * x2 + k27 * x3 - k3 * x2 * x4 + (k4 + k5) * x14, # x2
    k26 * x2 - k27 * x3 - k14 * x3 * x6 + (k15 + k16) * x15, # x3
    -k3 * x2 * x4 - k9 * x4 * x10 + k4 * x14 + k8 * x16 + (k10 + k11) * x18, # x4
    -k28 * x5 + k29 * x7 - k6 * x5 * x8 + k5 * x14 + k7 * x16, # x5
    -k14 * x3 * x6 - k20 * x6 * x11 + k15 * x15 + k19 * x17 + (k21 + k22) * x19, # x6
    k28 * x5 - k29 * x7 - k17 * x7 * x9 + k16 * x15 + k18 * x17, # x7
    -k6 * x5 * x8 + (k7 + k8) * x16, # x8
    -k17 * x7 * x9 + (k18 + k19) * x17, # x9
    k12 - (k13 + k30) * x10 - k9 * x4 * x10 + k31 * x11 + k10 * x18, # x10
    -k23 * x11 + k30 * x10 - k31 * x11 - k20 * x6 * x11 - k24 * x11 * x12 + k25 * x13 + k21 * x19, # x11
    -k24 * x11 * x12 + k25 * x13, # x12
    -k24 * x11 * x12 + k25 * x13, # x13
    k3 * x2 * x4 - (k4 + k5) * x14, # x14
    k14 * x3 * x6 - (k15 + k16) * x15, # x15
    -k6 * x5 * x8 + (k7 + k8) * x16, # x16
    -k17 * x7 * x9 + (k18 + k19) * x17, # x17
    k9 * x4 * x10 - (k10 + k11) * x18, # x18
    k20 * x6 * x11 - (k21 + k22) * x19]; # x19

conservationLaws = [
    (x1 + x2 + x3 + x14 + x15) - c1,
    (x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19) - c2,
    (x8 + x16) - c3,
    (x9 + x17) - c4,
    (x12 + x13) - c5];

system = vcat([steadyStateEq for (i, steadyStateEq) in enumerate(steadyStateEqs) if i ∉ [3, 4, 8, 9, 12]],
    conservationLaws)


19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -k1*x1 + k2*x2
 k1*x1 - k3*x2*x4 + (-k2 - k26)*x2 + k27*x3 + (k4 + k5)*x14
 -k6*x5*x8 - k28*x5 + k29*x7 + k5*x14 + k7*x16
 -k14*x3*x6 - k20*x6*x11 + k15*x15 + k19*x17 + (k21 + k22)*x19
 k28*x5 - k17*x7*x9 - k29*x7 + k16*x15 + k18*x17
 -k9*x4*x10 + (-k13 - k30)*x10 + k31*x11 + k10*x18 + k12
 -k20*x6*x11 + k30*x10 - k24*x11*x12 + (-k23 - k31)*x11 + k25*x13 + k21*x19
 -k24*x11*x12 + k25*x13
 k3*x2*x4 + (-k4 - k5)*x14
 k14*x3*x6 + (-k15 - k16)*x15
 -k6*x5*x8 + (k7 + k8)*x16
 -k17*x7*x9 + (k18 + k19)*x17
 k9*x4*x10 + (-k10 - k11)*x18
 k20*x6*x11 + (-k21 - k22)*x19
 x1 + x2 + x3 + x14 + x15 - c1
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 - c2
 x8 + x16 - c3
 x9 + x17 - c4
 x12 + x13 - c5

In [3]:
# Make a choice of parameters
number_of_parameters = ngens(coefficient_ring(parent(first(system))))
target_parameters = collect(1:number_of_parameters)
target_system = specialize(system, target_parameters)

19-element Vector{QQMPolyRingElem}:
 -x1 + 2*x2
 x1 - 3*x2*x4 - 28*x2 + 27*x3 + 9*x14
 -6*x5*x8 - 28*x5 + 29*x7 + 5*x14 + 7*x16
 -14*x3*x6 - 20*x6*x11 + 15*x15 + 19*x17 + 43*x19
 28*x5 - 17*x7*x9 - 29*x7 + 16*x15 + 18*x17
 -9*x4*x10 - 43*x10 + 31*x11 + 10*x18 + 12
 -20*x6*x11 + 30*x10 - 24*x11*x12 - 54*x11 + 25*x13 + 21*x19
 -24*x11*x12 + 25*x13
 3*x2*x4 - 9*x14
 14*x3*x6 - 31*x15
 -6*x5*x8 + 15*x16
 -17*x7*x9 + 37*x17
 9*x4*x10 - 21*x18
 20*x6*x11 - 43*x19
 x1 + x2 + x3 + x14 + x15 - 32
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 - 33
 x8 + x16 - 34
 x9 + x17 - 35
 x12 + x13 - 36

## Embedding in vertical family

In [4]:
F, target_parameters = vertical_embedding(target_system)

(AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}[-a[1]*x1 + 2*a[2]*x2, a[1]*x1 - 3*a[3]*x2*x4 - 28*a[2]*x2 + 27*a[4]*x3 + 9*a[5]*x14, -6*a[6]*x5*x8 - 28*a[7]*x5 + 29*a[8]*x7 + 5*a[5]*x14 + 7*a[9]*x16, -14*a[10]*x3*x6 - 20*a[11]*x6*x11 + 15*a[12]*x15 + 19*a[13]*x17 + 43*a[14]*x19, 28*a[7]*x5 - 17*a[15]*x7*x9 - 29*a[8]*x7 + 16*a[12]*x15 + 18*a[13]*x17, -9*a[16]*x4*x10 - 43*a[17]*x10 + 31*a[18]*x11 + 10*a[19]*x18 + 12*a[20], -20*a[11]*x6*x11 + 30*a[17]*x10 - 24*a[21]*x11*x12 - 54*a[18]*x11 + 25*a[22]*x13 + 21*a[14]*x19, -24*a[21]*x11*x12 + 25*a[22]*x13, 3*a[3]*x2*x4 - 9*a[5]*x14, 14*a[10]*x3*x6 - 31*a[12]*x15, -6*a[6]*x5*x8 + 15*a[9]*x16, -17*a[15]*x7*x9 + 37*a[13]*x17, 9*a[16]*x4*x10 - 21*a[19]*x18, 20*a[11]*x6*x11 - 43*a[14]*x19, a[1]*x1 + a[2]*x2 + a[4]*x3 + a[5]*x14 + a[12]*x15 - 32*a[20], a[23]*x4 + a[7]*x5 + a[24]*x6 + a[8]*x7 + a[5]*x14 + a[12]*x15 + a[9]*x16 + a[13]*x17 + a[19]*x18 + a[14]*x19 - 33*a[20], a[25]*x8 + a[9]*x16 - 34*a[20], a[26]*x9 + a[13]*x17 - 35*a[20], a[27]*x12 + 

## Pertubation of parameters
This need to be repeated until a transversal intersection is found in next step.

In [5]:
m = length(target_parameters)
Kt, t = rational_function_field(QQ, "t")

v = [-2, 5, -51, -98, -81, 73, 88, 94, 60, 30, 31, -95, 26, 91, -13, -31, -83, 42, 70, -19, 5, 54, 23, -92, 31, -26, -19]
#v = rand(-100:100, m)

perturbed_parameters = (t .^ v) .* target_parameters;

In [6]:
linear_part, binomial_part = modify_vertically(F)
display(linear_part)
display(binomial_part)

19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -y[1] + 2*y[2]
 y[1] - 28*y[2] - 3*y[3] + 27*y[4] + 9*y[5]
 5*y[5] - 6*y[6] - 28*y[7] + 29*y[8] + 7*y[9]
 -14*y[10] - 20*y[11] + 15*y[12] + 19*y[13] + 43*y[14]
 28*y[7] - 29*y[8] + 16*y[12] + 18*y[13] - 17*y[15]
 -9*y[16] - 43*y[17] + 31*y[18] + 10*y[19] + 12*y[20]
 -20*y[11] + 21*y[14] + 30*y[17] - 54*y[18] - 24*y[21] + 25*y[22]
 -24*y[21] + 25*y[22]
 3*y[3] - 9*y[5]
 14*y[10] - 31*y[12]
 -6*y[6] + 15*y[9]
 37*y[13] - 17*y[15]
 9*y[16] - 21*y[19]
 20*y[11] - 43*y[14]
 y[1] + y[2] + y[4] + y[5] + y[12] - 32*y[20]
 y[5] + y[7] + y[8] + y[9] + y[12] + y[13] + y[14] + y[19] - 33*y[20] + y[23] + y[24]
 y[9] - 34*y[20] + y[25]
 y[13] - 35*y[20] + y[26]
 -36*y[20] + y[22] + y[27]

27-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -a[1]*x1 + y[1]
 -a[2]*x2 + y[2]
 -a[3]*x2*x4 + y[3]
 -a[4]*x3 + y[4]
 -a[5]*x14 + y[5]
 -a[6]*x5*x8 + y[6]
 -a[7]*x5 + y[7]
 -a[8]*x7 + y[8]
 -a[9]*x16 + y[9]
 -a[10]*x3*x6 + y[10]
 ⋮
 -a[19]*x18 + y[19]
 y[20] - a[20]
 -a[21]*x11*x12 + y[21]
 -a[22]*x13 + y[22]
 -a[23]*x4 + y[23]
 -a[24]*x6 + y[24]
 -a[25]*x8 + y[25]
 -a[26]*x9 + y[26]
 -a[27]*x12 + y[27]

## Tropicalizations

In [7]:
Kaxy = parent(first(binomial_part));
Ka = coefficient_ring(Kaxy);
K = base_ring(Ka);
Kx, x = polynomial_ring(K, symbols(parent(first(F))));

In [8]:
# Tropicalize the linear part over QQ
linear_part_specialized = specialize(linear_part, K.(ones(Int, ngens(Ka))))
nu_K = tropical_semiring_map(K)
@time TropL = tropical_linear_space(ideal(linear_part_specialized), nu_K)

 47.666207 seconds (715.96 M allocations: 5.592 GiB, 0.14% gc time, 2.65% compilation time)


Min tropical linear space

In [9]:
length(maximal_polyhedra(TropL))

78983

In [ ]:
Ktx, x = polynomial_ring(Kt, symbols(Kx))
Ktxy, xy = polynomial_ring(Kt, symbols(Kaxy));

In [ ]:
# Tropicalize the binomial part over QQt
binomial_part_specialized =
    hom(Kaxy, Ktxy, hom(Ka, Kt, perturbed_parameters), gens(Ktxy)).(binomial_part)
nu = tropical_semiring_map(Kt, t)
time_TropB = @elapsed TropB = Oscar.tropical_variety_binomial(ideal(binomial_part_specialized), nu)

## Computation of tropical intersection points

In [10]:
@time pts, mults = tropical_stable_intersection_linear_binomial(TropL, TropB)
projected_pts = [w[1:ngens(Kx)] for w in pts]
grc = sum(mults)

display(projected_pts)
display(mults)
display(grc)

UndefVarError: UndefVarError: `TropB` not defined

## Computation of initials and homotopies for a given point

In [11]:
# Substitution homomorphism Kxy -> Kx with y -> target_parametrs.*monomial_vector
Kxy, xy = polynomial_ring(K, symbols(Kaxy))
target_parameters = (c -> evaluate(c, QQ(1))).(perturbed_parameters)
monomial_vector = -hom(Kaxy, Kx, hom(Ka, K, ones(Int, m)), vcat(gens(Kx), zeros(Kx, m))).(binomial_part)
target_monomial_vector = target_parameters .* monomial_vector
substitute_y_by_monomials = hom(Kxy, Kx, vcat(gens(Kx), target_monomial_vector))

# Substitution homomorphism Kxy -> Ktx with y -> perturbed_parameters.*monomial_vector
perturbed_monomial_vector = perturbed_parameters .* hom(Kx, Ktx, gens(Ktx)).(monomial_vector)
substitute_y_by_perturbed_monomials = hom(Kxy, Ktx, vcat(gens(Ktx), perturbed_monomial_vector));


UndefVarError: UndefVarError: `Ktx` not defined

In [12]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

UndefVarError: UndefVarError: `pts` not defined

In [13]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

UndefVarError: UndefVarError: `w` not defined

## Solve start system and trace along homotopy

In [14]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

UndefVarError: UndefVarError: `initials` not defined

In [15]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

UndefVarError: UndefVarError: `H` not defined

## Functions that put the above together

In [16]:
# Computation of tropical intersection data
grc, projected_pts, initial_systems, tropical_groebner_bases, perturbed_parameters =
    tropical_root_count_with_homotopy_data_vertical(F, perturbed_parameters=perturbed_parameters, verbose=true)

## Function that solves the full system

In [ ]:
# Function that uses all of the above to solve the system
sols = tropical_solve(F, target_parameters; type_of_system=:vertical, verbose=true)

In [ ]:
# Certification
F_target_HC = HC_system_from_Oscar_system(target_system)
HC.certify(F_target_HC, sols)

Things to do:
* Check why certification fails