In [ ]:
using TropicalHomotopies, Oscar

## Construction of the system

In [2]:
# Define ring of parameters
A, (k1, k2, k3, k4, k5, k6, k7, k8, k9, k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k30, k31, c1, c2, c3, c4, c5) =
    polynomial_ring(QQ, ["k1", "k2", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10", "k11", "k12", "k13", "k14", "k15", "k16", "k17", "k18", "k19", "k20", "k21", "k22", "k23", "k24", "k25", "k26", "k27", "k28", "k29", "k30", "k31", "c1", "c2", "c3", "c4", "c5"]);

# Define ring of parameterized polynomials
B, (x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19) = polynomial_ring(A, ["x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18", "x19"]);

# Define the square(!) system of steady state equations and conservation laws
steadyStateEqs = [
    -k1 * x1 + k2 * x2, # x1
    k1 * x1 - (k2 + k26) * x2 + k27 * x3 - k3 * x2 * x4 + (k4 + k5) * x14, # x2
    k26 * x2 - k27 * x3 - k14 * x3 * x6 + (k15 + k16) * x15, # x3
    -k3 * x2 * x4 - k9 * x4 * x10 + k4 * x14 + k8 * x16 + (k10 + k11) * x18, # x4
    -k28 * x5 + k29 * x7 - k6 * x5 * x8 + k5 * x14 + k7 * x16, # x5
    -k14 * x3 * x6 - k20 * x6 * x11 + k15 * x15 + k19 * x17 + (k21 + k22) * x19, # x6
    k28 * x5 - k29 * x7 - k17 * x7 * x9 + k16 * x15 + k18 * x17, # x7
    -k6 * x5 * x8 + (k7 + k8) * x16, # x8
    -k17 * x7 * x9 + (k18 + k19) * x17, # x9
    k12 - (k13 + k30) * x10 - k9 * x4 * x10 + k31 * x11 + k10 * x18, # x10
    -k23 * x11 + k30 * x10 - k31 * x11 - k20 * x6 * x11 - k24 * x11 * x12 + k25 * x13 + k21 * x19, # x11
    -k24 * x11 * x12 + k25 * x13, # x12
    -k24 * x11 * x12 + k25 * x13, # x13
    k3 * x2 * x4 - (k4 + k5) * x14, # x14
    k14 * x3 * x6 - (k15 + k16) * x15, # x15
    -k6 * x5 * x8 + (k7 + k8) * x16, # x16
    -k17 * x7 * x9 + (k18 + k19) * x17, # x17
    k9 * x4 * x10 - (k10 + k11) * x18, # x18
    k20 * x6 * x11 - (k21 + k22) * x19]; # x19

conservationLaws = [
    (x1 + x2 + x3 + x14 + x15) - c1,
    (x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19) - c2,
    (x8 + x16) - c3,
    (x9 + x17) - c4,
    (x12 + x13) - c5];

system = vcat([steadyStateEq for (i, steadyStateEq) in enumerate(steadyStateEqs) if i ∉ [3, 4, 8, 9, 12]],
    conservationLaws)


19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -k1*x1 + k2*x2
 k1*x1 - k3*x2*x4 + (-k2 - k26)*x2 + k27*x3 + (k4 + k5)*x14
 -k6*x5*x8 - k28*x5 + k29*x7 + k5*x14 + k7*x16
 -k14*x3*x6 - k20*x6*x11 + k15*x15 + k19*x17 + (k21 + k22)*x19
 k28*x5 - k17*x7*x9 - k29*x7 + k16*x15 + k18*x17
 -k9*x4*x10 + (-k13 - k30)*x10 + k31*x11 + k10*x18 + k12
 -k20*x6*x11 + k30*x10 - k24*x11*x12 + (-k23 - k31)*x11 + k25*x13 + k21*x19
 -k24*x11*x12 + k25*x13
 k3*x2*x4 + (-k4 - k5)*x14
 k14*x3*x6 + (-k15 - k16)*x15
 -k6*x5*x8 + (k7 + k8)*x16
 -k17*x7*x9 + (k18 + k19)*x17
 k9*x4*x10 + (-k10 - k11)*x18
 k20*x6*x11 + (-k21 - k22)*x19
 x1 + x2 + x3 + x14 + x15 - c1
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 - c2
 x8 + x16 - c3
 x9 + x17 - c4
 x12 + x13 - c5

In [3]:
# Make a choice of parameters
number_of_parameters = ngens(coefficient_ring(parent(first(system))))
#target_parameters = collect(1:number_of_parameters)
target_parameters = rand(-100:100, number_of_parameters)
target_system = specialize(system, target_parameters)

19-element Vector{QQMPolyRingElem}:
 -89*x1 + 18*x2
 89*x1 - 90*x2*x4 - x2 - 19*x3 - 31*x14
 -32*x5*x8 + 48*x5 - 44*x7 - 8*x14 - 95*x16
 -31*x3*x6 - 80*x6*x11 + 47*x15 + 15*x17 - 113*x19
 -48*x5 - 82*x7*x9 + 44*x7 - 48*x15 - 28*x17
 -28*x4*x10 - 156*x10 - 16*x11 - 69*x18 + 84
 -80*x6*x11 + 60*x10 - 72*x11*x12 + 8*x11 - 18*x13 - 50*x19
 -72*x11*x12 - 18*x13
 90*x2*x4 + 31*x14
 31*x3*x6 + x15
 -32*x5*x8 - 135*x16
 -82*x7*x9 - 13*x17
 28*x4*x10 + 113*x18
 80*x6*x11 + 113*x19
 x1 + x2 + x3 + x14 + x15 - 95
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 + 73
 x8 + x16 + 19
 x9 + x17 + 87
 x12 + x13 - 22

## Embedding in vertical family

In [4]:
F, target_parameters = vertical_embedding(target_system)

(AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}[-89*a[1]*x1 + 18*a[2]*x2, 89*a[1]*x1 - 90*a[3]*x2*x4 - a[2]*x2 - 19*a[4]*x3 - 31*a[5]*x14, -32*a[6]*x5*x8 + 48*a[7]*x5 - 44*a[8]*x7 - 8*a[5]*x14 - 95*a[9]*x16, -31*a[10]*x3*x6 - 80*a[11]*x6*x11 + 47*a[12]*x15 + 15*a[13]*x17 - 113*a[14]*x19, -48*a[7]*x5 - 82*a[15]*x7*x9 + 44*a[8]*x7 - 48*a[12]*x15 - 28*a[13]*x17, -28*a[16]*x4*x10 - 156*a[17]*x10 - 16*a[18]*x11 - 69*a[19]*x18 + 84*a[20], -80*a[11]*x6*x11 + 60*a[17]*x10 - 72*a[21]*x11*x12 + 8*a[18]*x11 - 18*a[22]*x13 - 50*a[14]*x19, -72*a[21]*x11*x12 - 18*a[22]*x13, 90*a[3]*x2*x4 + 31*a[5]*x14, 31*a[10]*x3*x6 + a[12]*x15, -32*a[6]*x5*x8 - 135*a[9]*x16, -82*a[15]*x7*x9 - 13*a[13]*x17, 28*a[16]*x4*x10 + 113*a[19]*x18, 80*a[11]*x6*x11 + 113*a[14]*x19, a[1]*x1 + a[2]*x2 + a[4]*x3 + a[5]*x14 + a[12]*x15 - 95*a[20], a[23]*x4 + a[7]*x5 + a[24]*x6 + a[8]*x7 + a[5]*x14 + a[12]*x15 + a[9]*x16 + a[13]*x17 + a[19]*x18 + a[14]*x19 + 73*a[20], a[25]*x8 + a[9]*x16 + 19*a[20], a[26]*x9 + a[13]*x17 + 87*a[20

## Pertubation of parameters
This need to be repeated until a transversal intersection is found in next step.

In [5]:
m = length(target_parameters)
Kt, t = rational_function_field(QQ, "t")

v = [-2, 5, -51, -98, -81, 73, 88, 94, 60, 30, 31, -95, 26, 91, -13, -31, -83, 42, 70, -19, 5, 54, 23, -92, 31, -26, -19]
#v = rand(-100:100, m)

perturbed_parameters = (t .^ v) .* target_parameters;

In [6]:
linear_part, binomial_part = modify_vertically(F)
display(linear_part)
display(binomial_part)

19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -89*y[1] + 18*y[2]
 89*y[1] - y[2] - 90*y[3] - 19*y[4] - 31*y[5]
 -8*y[5] - 32*y[6] + 48*y[7] - 44*y[8] - 95*y[9]
 -31*y[10] - 80*y[11] + 47*y[12] + 15*y[13] - 113*y[14]
 -48*y[7] + 44*y[8] - 48*y[12] - 28*y[13] - 82*y[15]
 -28*y[16] - 156*y[17] - 16*y[18] - 69*y[19] + 84*y[20]
 -80*y[11] - 50*y[14] + 60*y[17] + 8*y[18] - 72*y[21] - 18*y[22]
 -72*y[21] - 18*y[22]
 90*y[3] + 31*y[5]
 31*y[10] + y[12]
 -32*y[6] - 135*y[9]
 -13*y[13] - 82*y[15]
 28*y[16] + 113*y[19]
 80*y[11] + 113*y[14]
 y[1] + y[2] + y[4] + y[5] + y[12] - 95*y[20]
 y[5] + y[7] + y[8] + y[9] + y[12] + y[13] + y[14] + y[19] + 73*y[20] + y[23] + y[24]
 y[9] + 19*y[20] + y[25]
 y[13] + 87*y[20] + y[26]
 -22*y[20] + y[22] + y[27]

27-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -a[1]*x1 + y[1]
 -a[2]*x2 + y[2]
 -a[3]*x2*x4 + y[3]
 -a[4]*x3 + y[4]
 -a[5]*x14 + y[5]
 -a[6]*x5*x8 + y[6]
 -a[7]*x5 + y[7]
 -a[8]*x7 + y[8]
 -a[9]*x16 + y[9]
 -a[10]*x3*x6 + y[10]
 ⋮
 -a[19]*x18 + y[19]
 y[20] - a[20]
 -a[21]*x11*x12 + y[21]
 -a[22]*x13 + y[22]
 -a[23]*x4 + y[23]
 -a[24]*x6 + y[24]
 -a[25]*x8 + y[25]
 -a[26]*x9 + y[26]
 -a[27]*x12 + y[27]

## Tropicalizations

In [7]:
Kaxy = parent(first(binomial_part));
Ka = coefficient_ring(Kaxy);
K = base_ring(Ka);
Kx, x = polynomial_ring(K, symbols(parent(first(F))));

In [ ]:
# Tropicalize the linear part over QQ
linear_part_specialized = specialize(linear_part, K.(ones(Int, ngens(Ka))))
nu_K = tropical_semiring_map(K)
@time TropL = tropical_linear_space(ideal(linear_part_specialized), nu_K)

In [ ]:
length(maximal_polyhedra(TropL))

In [ ]:
lineality_space(TropL)

In [ ]:
Ktx, x = polynomial_ring(Kt, symbols(Kx))
Ktxy, xy = polynomial_ring(Kt, symbols(Kaxy))

binomial_part_specialized =
    hom(Kaxy, Ktxy, hom(Ka, Kt, perturbed_parameters), gens(Ktxy)).(binomial_part)

# Tropicalize the binomial part over QQt
nu = tropical_semiring_map(Kt, t)
@time TropB = Oscar.tropical_variety_binomial(ideal(binomial_part_specialized), nu)

## Computation of tropical intersection points

In [ ]:
@time pts, mults = tropical_stable_intersection_linear_binomial(TropL, TropB)
projected_pts = [w[1:ngens(Kx)] for w in pts]
grc = sum(mults)

display(projected_pts)
display(mults)
display(grc)

## Computation of initials and homotopies for a given point

In [ ]:
# Substitution homomorphism Kxy -> Kx with y -> target_parametrs.*monomial_vector
Kxy, xy = polynomial_ring(K, symbols(Kaxy))
target_parameters = (c -> evaluate(c, QQ(1))).(perturbed_parameters)
monomial_vector = -hom(Kaxy, Kx, hom(Ka, K, ones(Int, m)), vcat(gens(Kx), zeros(Kx, m))).(binomial_part)
target_monomial_vector = target_parameters .* monomial_vector
substitute_y_by_monomials = hom(Kxy, Kx, vcat(gens(Kx), target_monomial_vector))

# Substitution homomorphism Kxy -> Ktx with y -> perturbed_parameters.*monomial_vector
perturbed_monomial_vector = perturbed_parameters .* hom(Kx, Ktx, gens(Ktx)).(monomial_vector)
substitute_y_by_perturbed_monomials = hom(Kxy, Ktx, vcat(gens(Ktx), perturbed_monomial_vector));


In [ ]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

In [ ]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

## Solve start system and trace along homotopy

In [ ]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

In [ ]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

In [ ]:
# Choice of point
w = pts[2]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)
## Solve start system and trace along homotopy
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

H_tracker = HC.Tracker(H_HC, options=HC.TrackerOptions(automatic_differentiation = 3))
t1 = exp(2 * pi * im * rand())
res1 = HC.track.(H_tracker, start_solutions, 0, t1)
sol1 = [HC.solution(r) for r in res1 if r.return_code == :success]
res = HC.track.(H_tracker, sol1, t1, 1)
new_solutions = [HC.solution(r) for r in res if r.return_code == :success]


In [ ]:
H_HC_rev = HC.Homotopy(HC.subs(H_HC.expressions,H_HC.t=>(1-H_HC.t)),H_HC.variables,H_HC.t)
R = HC.solve(H_HC_rev, start_solutions)
HC.path_results(R)

In [ ]:
sols = Vector{ComplexF64}[]
for w in pts
    # Compute the tropical Gröbner basis and initial for the linear part
    G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
    initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

    # Substitute the y variables by the monomials
    initials = substitute_y_by_monomials.(initials_linear)

    # Tropical Gröbner basis
    G = substitute_y_by_perturbed_monomials.(G_linear)
    # Homotopy in OSCAR format
    projected_point = w[1:ngens(Kx)]
    H = homotopy_from_tropical_data(G,projected_point)
    ## Solve start system and trace along homotopy
    # Solve start system
    S_HC = HC_system_from_Oscar_system(initials)
    start_solutions = solve_binomial_system(S_HC)
    # Homotopy in HC format
    H_HC = export_homotopy_from_oscar_to_HC(H)
    new_sols = trace_solutions_along_homotopy(H_HC, start_solutions)
    display(new_sols)
    append!(sols, new_sols)
end

# Certification
F_target_HC = HC_system_from_Oscar_system(target_system)
HC.certify(F_target_HC, sols)

In [ ]:
sols

In [ ]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

In [ ]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

## Solve start system and trace along homotopy

In [ ]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

In [ ]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

In [ ]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

In [ ]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

## Solve start system and trace along homotopy

In [ ]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

In [ ]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

## Functions that put the above together

In [ ]:
# Computation of tropical intersection data
grc, projected_pts, initial_systems, tropical_groebner_bases, perturbed_parameters =
    tropical_root_count_with_homotopy_data_vertical(F, perturbed_parameters=perturbed_parameters, verbose=true)

display(grc)
display(projected_pts)
display(initial_systems)
display(tropical_groebner_bases)