In [1]:
include("../src/main.jl");

## Construction of the system

In [72]:
# Define ring of parameters
A, (k1, k2, k3, k4, k5, k6, k7, k8, k9, k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k30, k31, c1, c2, c3, c4, c5) =
    polynomial_ring(QQ, ["k1", "k2", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10", "k11", "k12", "k13", "k14", "k15", "k16", "k17", "k18", "k19", "k20", "k21", "k22", "k23", "k24", "k25", "k26", "k27", "k28", "k29", "k30", "k31", "c1", "c2", "c3", "c4", "c5"]);

# Define ring of parameterized polynomials
B, (x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19) = polynomial_ring(A, ["x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18", "x19"]);

# Define the square(!) system of steady state equations and conservation laws
steadyStateEqs = [
    -k1 * x1 + k2 * x2, # x1
    k1 * x1 - (k2 + k26) * x2 + k27 * x3 - k3 * x2 * x4 + (k4 + k5) * x14, # x2
    k26 * x2 - k27 * x3 - k14 * x3 * x6 + (k15 + k16) * x15, # x3
    -k3 * x2 * x4 - k9 * x4 * x10 + k4 * x14 + k8 * x16 + (k10 + k11) * x18, # x4
    -k28 * x5 + k29 * x7 - k6 * x5 * x8 + k5 * x14 + k7 * x16, # x5
    -k14 * x3 * x6 - k20 * x6 * x11 + k15 * x15 + k19 * x17 + (k21 + k22) * x19, # x6
    k28 * x5 - k29 * x7 - k17 * x7 * x9 + k16 * x15 + k18 * x17, # x7
    -k6 * x5 * x8 + (k7 + k8) * x16, # x8
    -k17 * x7 * x9 + (k18 + k19) * x17, # x9
    k12 - (k13 + k30) * x10 - k9 * x4 * x10 + k31 * x11 + k10 * x18, # x10
    -k23 * x11 + k30 * x10 - k31 * x11 - k20 * x6 * x11 - k24 * x11 * x12 + k25 * x13 + k21 * x19, # x11
    -k24 * x11 * x12 + k25 * x13, # x12
    -k24 * x11 * x12 + k25 * x13, # x13
    k3 * x2 * x4 - (k4 + k5) * x14, # x14
    k14 * x3 * x6 - (k15 + k16) * x15, # x15
    -k6 * x5 * x8 + (k7 + k8) * x16, # x16
    -k17 * x7 * x9 + (k18 + k19) * x17, # x17
    k9 * x4 * x10 - (k10 + k11) * x18, # x18
    k20 * x6 * x11 - (k21 + k22) * x19]; # x19

conservationLaws = [
    (x1 + x2 + x3 + x14 + x15) - c1,
    (x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19) - c2,
    (x8 + x16) - c3,
    (x9 + x17) - c4,
    (x12 + x13) - c5];

system = vcat([steadyStateEq for (i, steadyStateEq) in enumerate(steadyStateEqs) if i ∉ [3, 4, 8, 9, 12]],
    conservationLaws)


19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -k1*x1 + k2*x2
 k1*x1 - k3*x2*x4 + (-k2 - k26)*x2 + k27*x3 + (k4 + k5)*x14
 -k6*x5*x8 - k28*x5 + k29*x7 + k5*x14 + k7*x16
 -k14*x3*x6 - k20*x6*x11 + k15*x15 + k19*x17 + (k21 + k22)*x19
 k28*x5 - k17*x7*x9 - k29*x7 + k16*x15 + k18*x17
 -k9*x4*x10 + (-k13 - k30)*x10 + k31*x11 + k10*x18 + k12
 -k20*x6*x11 + k30*x10 - k24*x11*x12 + (-k23 - k31)*x11 + k25*x13 + k21*x19
 -k24*x11*x12 + k25*x13
 k3*x2*x4 + (-k4 - k5)*x14
 k14*x3*x6 + (-k15 - k16)*x15
 -k6*x5*x8 + (k7 + k8)*x16
 -k17*x7*x9 + (k18 + k19)*x17
 k9*x4*x10 + (-k10 - k11)*x18
 k20*x6*x11 + (-k21 - k22)*x19
 x1 + x2 + x3 + x14 + x15 - c1
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 - c2
 x8 + x16 - c3
 x9 + x17 - c4
 x12 + x13 - c5

In [73]:
# Make a choice of parameters
number_of_parameters = ngens(coefficient_ring(parent(first(system))))
#target_parameters = collect(1:number_of_parameters)
target_parameters = rand(-100:100, number_of_parameters)
target_system = specialize(system, target_parameters)

19-element Vector{QQMPolyRingElem}:
 22*x1 - 35*x2
 -22*x1 - 80*x2*x4 - 31*x2 + 58*x3 - 56*x14
 51*x5*x8 - 10*x5 + 76*x7 - 4*x14 - 89*x16
 94*x3*x6 - 37*x6*x11 + 6*x15 - 70*x17 - 24*x19
 10*x5 - 15*x7*x9 - 76*x7 + 36*x15 + 23*x17
 40*x4*x10 + 150*x10 + 35*x11 + 17*x18 + 68
 -37*x6*x11 - 54*x10 + 53*x11*x12 - 62*x11 - 5*x13 + 22*x19
 53*x11*x12 - 5*x13
 80*x2*x4 + 56*x14
 -94*x3*x6 - 42*x15
 51*x5*x8 - 125*x16
 -15*x7*x9 - 47*x17
 -40*x4*x10 - 13*x18
 37*x6*x11 + 24*x19
 x1 + x2 + x3 + x14 + x15 + 52
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 + 15
 x8 + x16 + 77
 x9 + x17 + 98
 x12 + x13 + 86

## Embedding in vertical family

In [74]:
F, target_parameters = vertical_embedding(target_system)

(AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}[22*a[1]*x1 - 35*a[2]*x2, -22*a[1]*x1 - 80*a[3]*x2*x4 - 31*a[2]*x2 + 58*a[4]*x3 - 56*a[5]*x14, 51*a[6]*x5*x8 - 10*a[7]*x5 + 76*a[8]*x7 - 4*a[5]*x14 - 89*a[9]*x16, 94*a[10]*x3*x6 - 37*a[11]*x6*x11 + 6*a[12]*x15 - 70*a[13]*x17 - 24*a[14]*x19, 10*a[7]*x5 - 15*a[15]*x7*x9 - 76*a[8]*x7 + 36*a[12]*x15 + 23*a[13]*x17, 40*a[16]*x4*x10 + 150*a[17]*x10 + 35*a[18]*x11 + 17*a[19]*x18 + 68*a[20], -37*a[11]*x6*x11 - 54*a[17]*x10 + 53*a[21]*x11*x12 - 62*a[18]*x11 - 5*a[22]*x13 + 22*a[14]*x19, 53*a[21]*x11*x12 - 5*a[22]*x13, 80*a[3]*x2*x4 + 56*a[5]*x14, -94*a[10]*x3*x6 - 42*a[12]*x15, 51*a[6]*x5*x8 - 125*a[9]*x16, -15*a[15]*x7*x9 - 47*a[13]*x17, -40*a[16]*x4*x10 - 13*a[19]*x18, 37*a[11]*x6*x11 + 24*a[14]*x19, a[1]*x1 + a[2]*x2 + a[4]*x3 + a[5]*x14 + a[12]*x15 + 52*a[20], a[23]*x4 + a[7]*x5 + a[24]*x6 + a[8]*x7 + a[5]*x14 + a[12]*x15 + a[9]*x16 + a[13]*x17 + a[19]*x18 + a[14]*x19 + 15*a[20], a[25]*x8 + a[9]*x16 + 77*a[20], a[26]*x9 + a[13]*x17 + 98*a[20], 

## Pertubation of parameters
This need to be repeated until a transversal intersection is found in next step.

In [75]:
m = length(target_parameters)
Kt, t = rational_function_field(QQ, "t")

v = [-2, 5, -51, -98, -81, 73, 88, 94, 60, 30, 31, -95, 26, 91, -13, -31, -83, 42, 70, -19, 5, 54, 23, -92, 31, -26, -19]
#v = rand(-100:100, m)

perturbed_parameters = (t .^ v) .* target_parameters;

In [76]:
linear_part, binomial_part = modify_vertically(F)
display(linear_part)
display(binomial_part)

19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 22*y[1] - 35*y[2]
 -22*y[1] - 31*y[2] - 80*y[3] + 58*y[4] - 56*y[5]
 -4*y[5] + 51*y[6] - 10*y[7] + 76*y[8] - 89*y[9]
 94*y[10] - 37*y[11] + 6*y[12] - 70*y[13] - 24*y[14]
 10*y[7] - 76*y[8] + 36*y[12] + 23*y[13] - 15*y[15]
 40*y[16] + 150*y[17] + 35*y[18] + 17*y[19] + 68*y[20]
 -37*y[11] + 22*y[14] - 54*y[17] - 62*y[18] + 53*y[21] - 5*y[22]
 53*y[21] - 5*y[22]
 80*y[3] + 56*y[5]
 -94*y[10] - 42*y[12]
 51*y[6] - 125*y[9]
 -47*y[13] - 15*y[15]
 -40*y[16] - 13*y[19]
 37*y[11] + 24*y[14]
 y[1] + y[2] + y[4] + y[5] + y[12] + 52*y[20]
 y[5] + y[7] + y[8] + y[9] + y[12] + y[13] + y[14] + y[19] + 15*y[20] + y[23] + y[24]
 y[9] + 77*y[20] + y[25]
 y[13] + 98*y[20] + y[26]
 86*y[20] + y[22] + y[27]

27-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -a[1]*x1 + y[1]
 -a[2]*x2 + y[2]
 -a[3]*x2*x4 + y[3]
 -a[4]*x3 + y[4]
 -a[5]*x14 + y[5]
 -a[6]*x5*x8 + y[6]
 -a[7]*x5 + y[7]
 -a[8]*x7 + y[8]
 -a[9]*x16 + y[9]
 -a[10]*x3*x6 + y[10]
 ⋮
 -a[19]*x18 + y[19]
 y[20] - a[20]
 -a[21]*x11*x12 + y[21]
 -a[22]*x13 + y[22]
 -a[23]*x4 + y[23]
 -a[24]*x6 + y[24]
 -a[25]*x8 + y[25]
 -a[26]*x9 + y[26]
 -a[27]*x12 + y[27]

## Tropicalizations

In [77]:
Kaxy = parent(first(binomial_part));
Ka = coefficient_ring(Kaxy);
K = base_ring(Ka);
Kx, x = polynomial_ring(K, symbols(parent(first(F))));

In [78]:
# Tropicalize the linear part over QQ
linear_part_specialized = specialize(linear_part, K.(ones(Int, ngens(Ka))))
nu_K = tropical_semiring_map(K)
@time TropL = tropical_linear_space(ideal(linear_part_specialized), nu_K)

 68.087301 seconds (711.60 M allocations: 5.305 GiB, 0.09% gc time)


Min tropical linear space

In [79]:
length(maximal_polyhedra(TropL))

78983

In [80]:
lineality_space(TropL)

20-element SubObjectIterator{RayVector{QQFieldElem}}:
 [1, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 1, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 1, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 1, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 1, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 1  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0

In [81]:
Ktx, x = polynomial_ring(Kt, symbols(Kx))
Ktxy, xy = polynomial_ring(Kt, symbols(Kaxy))

binomial_part_specialized =
    hom(Kaxy, Ktxy, hom(Ka, Kt, perturbed_parameters), gens(Ktxy)).(binomial_part)

# Tropicalize the binomial part over QQt
nu = tropical_semiring_map(Kt, t)
@time TropB = Oscar.tropical_variety_binomial(ideal(binomial_part_specialized), nu)

  0.004412 seconds (15.38 k allocations: 1.823 MiB)


Min tropical variety

## Computation of tropical intersection points

In [85]:
@time pts, mults = tropical_stable_intersection_linear_binomial(TropL, TropB)
projected_pts = [w[1:ngens(Kx)] for w in pts]
grc = sum(mults)

display(projected_pts)
display(mults)
display(grc)

8-element Vector{Vector{QQFieldElem}}:
 [-17, -24, 79, 230, 132, 11, 126, -50, 7, 2, -123, 99, -73, 236, 215, 95, 94, 131, -172]
 [-17, -24, 79, 292, 194, 73, 188, -50, 7, 64, -61, 37, -73, 298, 277, 157, 156, 255, -48]
 [126, 119, 222, -52, -7, -271, -13, -50, 7, -280, -123, 99, -73, 97, 76, -44, -45, -433, -454]
 [-218, -225, -122, 292, -7, -128, -13, -50, -194, 64, 78, 0, 29, 97, -125, -44, -246, 255, -110]
 [91, 84, 187, -52, -42, -236, -48, -50, 42, -245, -123, 99, -73, 62, 76, -79, -45, -398, -419]
 [-235//2, -249//2, -43//2, 56, -42, -55//2, -48, -301//2, 42, 64, -45//2, 0, -143//2, -77//2, 76, -359//2, -45, 19, -110]
 [-156, -163, -60, 56, -42, 11, -48, -189, 42, -75, -200, 176, -73, -77, 76, -218, -45, -120, -249]
 [-17, -24, 79, 56, -308, -128, -314, 216, 308, 64, 78, 0, 29, 62, 76, -79, -45, 19, -110]

8-element Vector{Int64}:
 1
 1
 1
 1
 1
 2
 1
 1

9

 25.968961 seconds (94.13 M allocations: 14.966 GiB, 8.57% gc time, 0.31% compilation time)


## Computation of initials and homotopies for a given point

In [86]:
# Substitution homomorphism Kxy -> Kx with y -> target_parametrs.*monomial_vector
Kxy, xy = polynomial_ring(K, symbols(Kaxy))
target_parameters = (c -> evaluate(c, QQ(1))).(perturbed_parameters)
monomial_vector = -hom(Kaxy, Kx, hom(Ka, K, ones(Int, m)), vcat(gens(Kx), zeros(Kx, m))).(binomial_part)
target_monomial_vector = target_parameters .* monomial_vector
substitute_y_by_monomials = hom(Kxy, Kx, vcat(gens(Kx), target_monomial_vector))

# Substitution homomorphism Kxy -> Ktx with y -> perturbed_parameters.*monomial_vector
perturbed_monomial_vector = perturbed_parameters .* hom(Kx, Ktx, gens(Ktx)).(monomial_vector)
substitute_y_by_perturbed_monomials = hom(Kxy, Ktx, vcat(gens(Ktx), perturbed_monomial_vector));


In [87]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 -24//37*t^23*x4 + t^31*x6*x11 - 24//37//t^92*x6 - 19360//85211//t^13*x7*x9 - 1032//185*t^94*x7 + 180//1813//t^26*x9 - 240//37*t^60*x16 - 24//37*t^70*x18
 t^23*x4 + 1//t^92*x6 + 2420//6909//t^13*x7*x9 + 43//5*t^94*x7 - 15//98//t^26*x9 + 10*t^60*x16 + t^70*x18 + t^91*x19
 -161//741*t^23*x4 - 161//741//t^92*x6 - 380134//5119569//t^13*x7*x9 - 6923//3705*t^94*x7 + 9967//363090//t^26*x9 + 1//t^83*x10 - 1610//741*t^60*x16 - 227//1235*t^70*x18
 230//247*t^23*x4 + 230//247//t^92*x6 + 553846//1706523//t^13*x7*x9 + 1978//247*t^94*x7 - 8319//60515//t^26*x9 + t^42*x11 + 2300//247*t^60*x16 + 1114//1235*t^70*x18
 1//t^2*x1 + 1582675//4696146//t^13*x7*x9 - 290//1281//t^26*x9 + 3045//793*t^60*x16
 t^5*x2 + 3481885//16436511//t^13*x7*x9 - 1276//8967//t^26*x9 + 1914//793*t^60*x16
 1//t^98*x3 + 1320715//5478837//t^13*x7*x9 - 484//2989//t^26*x9 + 2178//793*t^60*x16
 -15//4606//

In [88]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 -24//37*t^334*x4 + x6*x11 - 24//37*x6 - 19360//85211*t^201*x7*x9 - 1032//185*t^301*x7 + 180//1813*t^62*x9 - 240//37*t^236*x16 - 24//37*t^282*x18
 t^334*x4 + x6 + 2420//6909*t^201*x7*x9 + 43//5*t^301*x7 - 15//98*t^62*x9 + 10*t^236*x16 + t^282*x18 + x19
 -161//741*t^334*x4 - 161//741*x6 - 380134//5119569*t^201*x7*x9 - 6923//3705*t^301*x7 + 9967//363090*t^62*x9 + x10 - 1610//741*t^236*x16 - 227//1235*t^282*x18
 230//247*t^334*x4 + 230//247*x6 + 553846//1706523*t^201*x7*x9 + 1978//247*t^301*x7 - 8319//60515*t^62*x9 + x11 + 2300//247*t^236*x16 + 1114//1235*t^282*x18
 x1 + 1582675//4696146*t^139*x7*x9 - 290//1281*x9 + 3045//793*t^174*x16
 x2 + 3481885//16436511*t^139*x7*x9 - 1276//8967*x9 + 1914//793*t^174*x16
 x3 + 1320715//5478837*t^139*x7*x9 - 484//2989*x9 + 2178//793*t^174*x16
 -15//4606*t^139*x7*x9 + 1//98*x9 + 1
 3225//122059*t^139*x7*x9 - 215//2597*x9 + x1

## Solve start system and trace along homotopy

In [264]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

1-element Vector{Vector{ComplexF64}}:
 [-22.185792349726785 + 0.0im, -13.945355191256835 + 0.0im, -15.8688524590164 + 0.0im, -43.879649916998645 + 0.0im, 3.091728124383842 + 0.0im, -0.6965922444183315 + 0.0im, 0.4068063321557688 + 0.0im, -77.00000000000003 + 0.0im, -98.00000000000004 + 0.0im, -0.15135135135135136 + 0.0im, 0.6486486486486487 + 0.0im, -12.50786163522013 + 0.0im, -86.00000000000003 + 0.0im, -874.1675768007855 + 0.0im, -24.740172327912898 + 0.0im, -97.12973075564281 + 0.0im, 12.723517197212347 + 0.0im, -20.434597882344484 + 0.0im, 0.6965922444183315 + 0.0im]

In [274]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

Vector{ComplexF64}[]

In [388]:
# Choice of point
w = pts[2]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)
## Solve start system and trace along homotopy
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

H_tracker = HC.Tracker(H_HC, options=HC.TrackerOptions(automatic_differentiation = 3))
t1 = exp(2 * pi * im * rand())
res1 = HC.track.(H_tracker, start_solutions, 0, t1)
sol1 = [HC.solution(r) for r in res1 if r.return_code == :success]
res = HC.track.(H_tracker, sol1, t1, 1)
new_solutions = [HC.solution(r) for r in res if r.return_code == :success]


1-element Vector{Vector{ComplexF64}}:
 [-17.092259051808238 + 2.6815964878133434e-38im, -10.743705689708033 + 1.6897731293070383e-38im, -12.225596129667762 + 1.9101783200862172e-38im, -0.756042515569837 - 1.3775324423698682e-40im, 0.041739039015892286 + 1.2914366647217514e-41im, -0.012228048231929418 - 5.739718509874451e-42im, 0.005491978817880564 + 2.3317606446364956e-42im, -75.71068281330336 + 1.1093727935885338e-37im, -98.17207200210949 + 1.4324615485093667e-37im, -0.5296409988530135 + 3.6734198463196485e-40im, 0.4678437931051801 + 2.2499696558707847e-39im, -14.43160242710804 + 9.4039548065783e-38im, -71.56839757289197 + 4.70197740328915e-38im, -11.603854680269762 + 1.3224311446750734e-38im, -0.33458444854620706 + 3.3290367357271814e-40im, -1.2893171866966402 + 1.4693679385278594e-39im, 0.17207200210947796 - 1.7793127380610797e-40im, -1.2320957326823185 + 2.204051907791789e-39im, 0.008819592053444214 - 2.2958874039497803e-41im]

In [380]:
H_HC_rev = HC.Homotopy(HC.subs(H_HC.expressions,H_HC.t=>(1-H_HC.t)),H_HC.variables,H_HC.t)
R = HC.solve(H_HC_rev, start_solutions)
HC.path_results(R)

1-element Vector{HomotopyContinuation.PathResult}:
 PathResult:
 • return_code → :terminated_step_size_too_small
 • solution → ComplexF64[-22.159763299277312 + 0.0im, -13.928994073831452 + 0.0im, -15.85023463573924 + 0.0im, -1118.8303061627357 + 0.0im, 78.74528424792447 + 0.0im, -17.76373673417427 + 0.0im, 10.361221611569011 + 0.0im, -76.9943235604412 + 0.0im, -98.00510173234885 + 0.0im, -1.1828349955259818 + 0.0im, 3.126438499562438 + 0.0im, -2.584846973198264 + 0.0im, -85.66246998033557 + 0.0im, -22263.11529166254 + 0.0im, -630.1567417369349 + 0.0im, -2473.6794768513932 + 0.0im, 324.08061003613795 + 0.0im, -4071.974277490254 + 0.0im, 85.61989690029652 + 0.0im]
 • accuracy → 8.4186e-17
 • residual → 1.819e-12
 • condition_jacobian → NaN
 • steps → 180 / 8
 • extended_precision → true
 • path_number → 1


In [223]:
sols = Vector{ComplexF64}[]
for w in pts
    # Compute the tropical Gröbner basis and initial for the linear part
    G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
    initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

    # Substitute the y variables by the monomials
    initials = substitute_y_by_monomials.(initials_linear)

    # Tropical Gröbner basis
    G = substitute_y_by_perturbed_monomials.(G_linear)
    # Homotopy in OSCAR format
    projected_point = w[1:ngens(Kx)]
    H = homotopy_from_tropical_data(G,projected_point)
    ## Solve start system and trace along homotopy
    # Solve start system
    S_HC = HC_system_from_Oscar_system(initials)
    start_solutions = solve_binomial_system(S_HC)
    # Homotopy in HC format
    H_HC = export_homotopy_from_oscar_to_HC(H)
    new_sols = trace_solutions_along_homotopy(H_HC, start_solutions)
    display(new_sols)
    append!(sols, new_sols)
end

# Certification
F_target_HC = HC_system_from_Oscar_system(target_system)
HC.certify(F_target_HC, sols)

1-element Vector{Vector{ComplexF64}}:
 [-1.0896563319326527 + 5.739718509874451e-42im, -0.6849268372148086 + 5.739718509874451e-42im, -0.7793995044168528 + 4.304788882405838e-42im, -49.031791357898825 + 0.0im, 0.1823004986476822 + 7.847271400218976e-44im, -0.8427292721646906 - 1.2555634240350361e-42im, 0.02398690771680029 - 1.961817850054744e-44im, -71.66933495591397 + 5.3809861030072976e-42im, -98.7560164209687 + 5.919084713308027e-42im, 0.7421842932559136 - 2.5111268480700722e-42im, -17.920350414097573 + 5.739718509874451e-42im, 0.45513309972068683 + 6.887662211849341e-41im, -86.45513309972068 - 6.887662211849341e-41im, -47.975985396774334 - 1.1479437019748901e-41im, -1.4700319296613593 + 1.1658803223182478e-42im, -5.330665044086037 - 1.4349296274686127e-42im, 0.7560164209686991 - 6.2778171201751805e-43im, 111.97115512625707 + 1.1479437019748901e-41im, -23.28225595300503 + 1.6501690715889046e-41im]

Vector{ComplexF64}[]

Vector{ComplexF64}[]

1-element Vector{Vector{ComplexF64}}:
 [0.9232168879454783 + 3.982729777831131e-59im, 0.5803077581371578 + 0.0im, 0.6603502075353864 + 3.982729777831131e-59im, 63.37815861730117 + 0.0im, 0.20107060774666768 + 0.0im, 1.0979428044911188 + 0.0im, 0.026456658914035223 + 7.778769097326427e-62im, -71.16208934252901 + 0.0im, -98.83452059585213 - 1.3065063810346254e-60im, 0.10566354213460045 + 0.0im, -0.04079602155352987 + 7.965459555662261e-59im, -151.52525011977968 + 8.156630584998156e-56im, 65.52525011977968 - 8.156630584998156e-56im, -52.541195917238895 + 0.0im, -1.622678936379126 - 4.9784122222889134e-60im, -5.837910657470989 + 0.0im, 0.8345205958521219 + 1.2446030555722283e-60im, -20.60541764145413 - 6.372367644529809e-58im, 0.0690538682380342 + 7.965459555662261e-59im]

Vector{ComplexF64}[]

1-element Vector{Vector{ComplexF64}}:
 [-17.092259051808234 + 5.345529420184391e-51im, -10.743705689708033 + 4.0091470651382935e-51im, -12.225596129667762 + 4.0091470651382935e-51im, -0.7560425155698371 + 4.343242653899818e-51im, 0.041739039015892286 + 5.22024357439882e-53im, -0.012228048231929415 - 4.176194859519056e-52im, 0.005491978817880563 + 4.176194859519056e-53im, -75.71068281330336 + 1.3363823550460978e-51im, -98.17207200210947 - 1.3363823550460978e-51im, -0.5296409988530135 - 2.088097429759528e-52im, 0.46784379310518004 - 2.5057169157114334e-52im, -14.431602427108038 - 8.552847072295026e-50im, -71.56839757289197 + 8.552847072295026e-50im, -11.603854680269762 - 1.0691058840368783e-50im, -0.33458444854620706 - 2.6727647100921956e-51im, -1.2893171866966402 - 1.3363823550460978e-51im, 0.17207200210947793 + 1.3363823550460978e-51im, -1.2320957326823188 + 1.0022867662845734e-50im, 0.008819592053444212 - 6.681911775230489e-52im]

1-element Vector{Vector{ComplexF64}}:
 [193.3655687455588 - 1.4437395444637849e-58im, 121.54407178292267 - 9.21006261123449e-59im, 138.30877133918787 - 1.0454665666806718e-58im, 3.9955332989353614 + 2.4892061111444567e-60im, -2231.5503049537742 - 2.8548207047493545e-55im, -0.6090927575581168 - 1.2834969010588605e-60im, -293.6250401254966 - 3.6959732338272893e-56im, 0.08466445981862826 - 1.057912597236394e-59im, -1.0347363179265667 + 1.2694951166836729e-58im, -212.54003777129674 - 2.102881322694837e-56im, 610.3194416054448 + 6.6272623503110015e-56im, -0.013291324338790187 + 1.4779661284920212e-60im, -85.9867086756612 - 1.4779661284920212e-60im, -693.7619801383677 + 9.458983222348935e-59im, 188.54356827069833 + 2.4892061111444567e-58im, -77.08466445981863 + 1.057912597236394e-59im, -96.96526368207343 - 1.2694951166836729e-58im, 2612.9563023759865 + 2.6509049401244006e-55im, 573.1009421714684 + 6.117472938748617e-56im]

1-element Vector{Vector{ComplexF64}}:
 [187.74204612151252 - 1.3237225813397952e-40im, 118.00928613352215 + 1.2663253962410507e-40im, 134.28642904849073 - 3.4438311059246704e-41im, 4.094406120111476 - 5.605193857299268e-42im, 616.14192307363 + 4.408103815583578e-39im, -0.6595215506127177 - 4.035739577255473e-43im, 81.07130566758288 + 6.198895990664407e-40im, -0.3050883531620024 + 1.883345136052554e-42im, 3.939885237837108 - 3.1209719397442326e-41im, 2.7756703731732926 + 3.0994479953322034e-40im, -9.842201638581686 - 9.183549615799121e-40im, 0.8323063594768475 + 2.3877229001077715e-39im, -86.83230635947685 - 2.3877229001077715e-39im, -690.2542048215419 - 1.133594405700204e-39im, 198.21644351801658 - 8.112334789737482e-40im, -76.694911646838 - 1.3595958220265105e-40im, -101.93988523783712 + 8.107352395197662e-41im, -34.96837465640871 - 4.040761830951613e-39im, -10.007180466102321 - 8.724372135009165e-40im]

CertificationResult
• 5 solution candidates given
• 5 certified solution intervals (5 real, 0 complex)
• 5 distinct certified solution intervals (5 real, 0 complex)

In [160]:
sols

7-element Vector{Vector{ComplexF64}}:
 [187.74204612151252 - 1.8669045833583425e-60im, 118.00928613352215 - 7.46761833343337e-60im, 134.28642904849073 - 4.6672614583958563e-60im, 4.094406120111476 + 1.750223046898446e-61im, 616.1419230736299 - 8.363732533445374e-58im, -0.6595215506127177 - 4.861730685829017e-62im, 81.07130566758288 - 1.095250688903561e-58im, -0.30508835316200245 - 4.083853776096374e-61im, 3.939885237837107 + 5.600713750075028e-60im, 2.7756703731732943 - 6.471935888975587e-59im, -9.842201638581692 + 1.095250688903561e-58im, 0.832306359476847 + 0.0im, -86.83230635947685 + 0.0im, -690.254204821542 + 1.3573952074834615e-59im, 198.2164435180166 + 6.223015277861142e-61im, -76.694911646838 + 1.5119982432928243e-60im, -101.9398852378371 - 3.422658402823628e-60im, -34.968374656408734 + 7.965459555662261e-58im, -10.007180466102325 + 1.493523666686674e-58im]
 [0.9232168879454784 - 3.447274937030595e-38im, 0.5803077581371577 + 5.531653713891502e-40im, 0.6603502075353864 - 2.465783

In [ ]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 -24//37*t^23*x4 + t^31*x6*x11 - 24//37//t^92*x6 - 19360//85211//t^13*x7*x9 - 1032//185*t^94*x7 + 180//1813//t^26*x9 - 240//37*t^60*x16 - 24//37*t^70*x18
 t^23*x4 + 1//t^92*x6 + 2420//6909//t^13*x7*x9 + 43//5*t^94*x7 - 15//98//t^26*x9 + 10*t^60*x16 + t^70*x18 + t^91*x19
 -161//741*t^23*x4 - 161//741//t^92*x6 - 380134//5119569//t^13*x7*x9 - 6923//3705*t^94*x7 + 9967//363090//t^26*x9 + 1//t^83*x10 - 1610//741*t^60*x16 - 227//1235*t^70*x18
 230//247*t^23*x4 + 230//247//t^92*x6 + 553846//1706523//t^13*x7*x9 + 1978//247*t^94*x7 - 8319//60515//t^26*x9 + t^42*x11 + 2300//247*t^60*x16 + 1114//1235*t^70*x18
 1//t^2*x1 + 1582675//4696146//t^13*x7*x9 - 290//1281//t^26*x9 + 3045//793*t^60*x16
 t^5*x2 + 3481885//16436511//t^13*x7*x9 - 1276//8967//t^26*x9 + 1914//793*t^60*x16
 1//t^98*x3 + 1320715//5478837//t^13*x7*x9 - 484//2989//t^26*x9 + 2178//793*t^60*x16
 -15//4606//

In [ ]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 -24//37*t^334*x4 + x6*x11 - 24//37*x6 - 19360//85211*t^201*x7*x9 - 1032//185*t^301*x7 + 180//1813*t^62*x9 - 240//37*t^236*x16 - 24//37*t^282*x18
 t^334*x4 + x6 + 2420//6909*t^201*x7*x9 + 43//5*t^301*x7 - 15//98*t^62*x9 + 10*t^236*x16 + t^282*x18 + x19
 -161//741*t^334*x4 - 161//741*x6 - 380134//5119569*t^201*x7*x9 - 6923//3705*t^301*x7 + 9967//363090*t^62*x9 + x10 - 1610//741*t^236*x16 - 227//1235*t^282*x18
 230//247*t^334*x4 + 230//247*x6 + 553846//1706523*t^201*x7*x9 + 1978//247*t^301*x7 - 8319//60515*t^62*x9 + x11 + 2300//247*t^236*x16 + 1114//1235*t^282*x18
 x1 + 1582675//4696146*t^139*x7*x9 - 290//1281*x9 + 3045//793*t^174*x16
 x2 + 3481885//16436511*t^139*x7*x9 - 1276//8967*x9 + 1914//793*t^174*x16
 x3 + 1320715//5478837*t^139*x7*x9 - 484//2989*x9 + 2178//793*t^174*x16
 -15//4606*t^139*x7*x9 + 1//98*x9 + 1
 3225//122059*t^139*x7*x9 - 215//2597*x9 + x1

## Solve start system and trace along homotopy

In [ ]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

1-element Vector{Vector{ComplexF64}}:
 [-22.185792349726785 + 0.0im, -13.945355191256835 + 0.0im, -15.8688524590164 + 0.0im, -43.879649916998645 + 0.0im, 3.091728124383842 + 0.0im, -0.6965922444183315 + 0.0im, 0.4068063321557688 + 0.0im, -77.00000000000003 + 0.0im, -98.00000000000004 + 0.0im, -0.15135135135135136 + 0.0im, 0.6486486486486487 + 0.0im, -12.50786163522013 + 0.0im, -86.00000000000003 + 0.0im, -874.1675768007855 + 0.0im, -24.740172327912898 + 0.0im, -97.12973075564281 + 0.0im, 12.723517197212347 + 0.0im, -20.434597882344484 + 0.0im, 0.6965922444183315 + 0.0im]

In [ ]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

1-element Vector{Vector{ComplexF64}}:
 [193.3655687455588 - 4.25401435010039e-62im, 121.54407178292267 - 2.3700937093416458e-62im, 138.30877133918787 - 3.0081958618567042e-62im, 3.9955332989353614 - 2.8486703237279396e-65im, -2231.5503049537742 + 1.804674430579731e-59im, -0.6090927575581168 - 7.833843390251834e-65im, -293.6250401254966 + 2.4114184201711924e-60im, 0.08466445981862826 + 6.741853099489457e-64im, -1.0347363179265667 - 8.204170532336466e-63im, -212.54003777129674 + 1.400178437518757e-60im, 610.3194416054448 - 3.8504907031765814e-60im, -0.013291324338790187 - 8.353132251348073e-65im, -85.9867086756612 - 5.735322918438918e-63im, -693.7619801383677 + 1.409901898890415e-61im, 188.54356827069833 - 2.035849724690901e-62im, -77.08466445981863 + 1.5648695645012148e-62im, -96.96526368207343 + 1.466115659945313e-62im, 2612.9563023759865 - 1.711329201411814e-59im, 573.1009421714684 - 3.6171276302567886e-60im]

In [ ]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 -24//37*t^23*x4 + t^31*x6*x11 - 24//37//t^92*x6 - 19360//85211//t^13*x7*x9 - 1032//185*t^94*x7 + 180//1813//t^26*x9 - 240//37*t^60*x16 - 24//37*t^70*x18
 t^23*x4 + 1//t^92*x6 + 2420//6909//t^13*x7*x9 + 43//5*t^94*x7 - 15//98//t^26*x9 + 10*t^60*x16 + t^70*x18 + t^91*x19
 -161//741*t^23*x4 - 161//741//t^92*x6 - 380134//5119569//t^13*x7*x9 - 6923//3705*t^94*x7 + 9967//363090//t^26*x9 + 1//t^83*x10 - 1610//741*t^60*x16 - 227//1235*t^70*x18
 230//247*t^23*x4 + 230//247//t^92*x6 + 553846//1706523//t^13*x7*x9 + 1978//247*t^94*x7 - 8319//60515//t^26*x9 + t^42*x11 + 2300//247*t^60*x16 + 1114//1235*t^70*x18
 1//t^2*x1 + 1582675//4696146//t^13*x7*x9 - 290//1281//t^26*x9 + 3045//793*t^60*x16
 t^5*x2 + 3481885//16436511//t^13*x7*x9 - 1276//8967//t^26*x9 + 1914//793*t^60*x16
 1//t^98*x3 + 1320715//5478837//t^13*x7*x9 - 484//2989//t^26*x9 + 2178//793*t^60*x16
 -15//4606//

In [ ]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 -24//37*t^334*x4 + x6*x11 - 24//37*x6 - 19360//85211*t^201*x7*x9 - 1032//185*t^301*x7 + 180//1813*t^62*x9 - 240//37*t^236*x16 - 24//37*t^282*x18
 t^334*x4 + x6 + 2420//6909*t^201*x7*x9 + 43//5*t^301*x7 - 15//98*t^62*x9 + 10*t^236*x16 + t^282*x18 + x19
 -161//741*t^334*x4 - 161//741*x6 - 380134//5119569*t^201*x7*x9 - 6923//3705*t^301*x7 + 9967//363090*t^62*x9 + x10 - 1610//741*t^236*x16 - 227//1235*t^282*x18
 230//247*t^334*x4 + 230//247*x6 + 553846//1706523*t^201*x7*x9 + 1978//247*t^301*x7 - 8319//60515*t^62*x9 + x11 + 2300//247*t^236*x16 + 1114//1235*t^282*x18
 x1 + 1582675//4696146*t^139*x7*x9 - 290//1281*x9 + 3045//793*t^174*x16
 x2 + 3481885//16436511*t^139*x7*x9 - 1276//8967*x9 + 1914//793*t^174*x16
 x3 + 1320715//5478837*t^139*x7*x9 - 484//2989*x9 + 2178//793*t^174*x16
 -15//4606*t^139*x7*x9 + 1//98*x9 + 1
 3225//122059*t^139*x7*x9 - 215//2597*x9 + x1

## Solve start system and trace along homotopy

In [ ]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

1-element Vector{Vector{ComplexF64}}:
 [-22.185792349726785 + 0.0im, -13.945355191256835 + 0.0im, -15.8688524590164 + 0.0im, -43.879649916998645 + 0.0im, 3.091728124383842 + 0.0im, -0.6965922444183315 + 0.0im, 0.4068063321557688 + 0.0im, -77.00000000000003 + 0.0im, -98.00000000000004 + 0.0im, -0.15135135135135136 + 0.0im, 0.6486486486486487 + 0.0im, -12.50786163522013 + 0.0im, -86.00000000000003 + 0.0im, -874.1675768007855 + 0.0im, -24.740172327912898 + 0.0im, -97.12973075564281 + 0.0im, 12.723517197212347 + 0.0im, -20.434597882344484 + 0.0im, 0.6965922444183315 + 0.0im]

In [ ]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

1-element Vector{Vector{ComplexF64}}:
 [193.3655687455588 - 4.25401435010039e-62im, 121.54407178292267 - 2.3700937093416458e-62im, 138.30877133918787 - 3.0081958618567042e-62im, 3.9955332989353614 - 2.8486703237279396e-65im, -2231.5503049537742 + 1.804674430579731e-59im, -0.6090927575581168 - 7.833843390251834e-65im, -293.6250401254966 + 2.4114184201711924e-60im, 0.08466445981862826 + 6.741853099489457e-64im, -1.0347363179265667 - 8.204170532336466e-63im, -212.54003777129674 + 1.400178437518757e-60im, 610.3194416054448 - 3.8504907031765814e-60im, -0.013291324338790187 - 8.353132251348073e-65im, -85.9867086756612 - 5.735322918438918e-63im, -693.7619801383677 + 1.409901898890415e-61im, 188.54356827069833 - 2.035849724690901e-62im, -77.08466445981863 + 1.5648695645012148e-62im, -96.96526368207343 + 1.466115659945313e-62im, 2612.9563023759865 - 1.711329201411814e-59im, 573.1009421714684 - 3.6171276302567886e-60im]

## Functions that put the above together

In [22]:
# Computation of tropical intersection data
grc, projected_pts, initial_systems, tropical_groebner_bases, perturbed_parameters =
    tropical_root_count_with_homotopy_data_vertical(F, perturbed_parameters=perturbed_parameters, verbose=true)

display(grc)
display(projected_pts)
display(initial_systems)
display(tropical_groebner_bases)

Time spent tropicalizing the linear part: 59.560788458
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.002771458
Time spent on stable intersection: 31.226437667


9

8-element Vector{Vector{QQFieldElem}}:
 [-17, -24, 79, 230, 132, 11, 126, -50, 7, 2, -123, 99, -73, 236, 215, 95, 94, 131, -172]
 [-17, -24, 79, 292, 194, 73, 188, -50, 7, 64, -61, 37, -73, 298, 277, 157, 156, 255, -48]
 [126, 119, 222, -52, -7, -271, -13, -50, 7, -280, -123, 99, -73, 97, 76, -44, -45, -433, -454]
 [-218, -225, -122, 292, -7, -128, -13, -50, -194, 64, 78, 0, 29, 97, -125, -44, -246, 255, -110]
 [91, 84, 187, -52, -42, -236, -48, -50, 42, -245, -123, 99, -73, 62, 76, -79, -45, -398, -419]
 [-235//2, -249//2, -43//2, 56, -42, -55//2, -48, -301//2, 42, 64, -45//2, 0, -143//2, -77//2, 76, -359//2, -45, 19, -110]
 [-156, -163, -60, 56, -42, 11, -48, -189, 42, -75, -200, 176, -73, -77, 76, -218, -45, -120, -249]
 [-17, -24, 79, 56, -308, -128, -314, 216, 308, 64, 78, 0, 29, 62, 76, -79, -45, 19, -110]

8-element Vector{Vector{QQMPolyRingElem}}:
 [x6*x11 + 43//20*x6, x6 + x19, -341//696*x6 + x10, -473//696*x6 + x11, x1 - 1728//3745*x9, x2 - 864//3745*x9, x3 - 832//3745*x9, -1//35*x9 + 1, -15//14*x9 + x11*x12, -36//35*x9 + x13, x8 - 34//35*x9, x3*x6 - 10013//8288*x7*x9, -323//592*x7*x9 + x15, -17//37*x7*x9 + x17, x2*x4 - 24//5*x16, x14 - 8//5*x16, x5*x8 - 5//2*x16, x4*x10 - 7//3*x18, x5 - 29//28*x7]
 [x1 - 1728//3745*x9, x2 - 864//3745*x9, x3 - 832//3745*x9, -27//2030*x9 + x10, -3//406*x9 + x11, -1//35*x9 + 1, -15//14*x9 + x11*x12, -36//35*x9 + x13, x6 - 33//35*x9, x8 - 34//35*x9, x6*x11 - 43//20*x19, x3*x6 - 10013//8288*x7*x9, -323//592*x7*x9 + x15, -17//37*x7*x9 + x17, x2*x4 - 24//5*x16, x14 - 8//5*x16, x5*x8 - 5//2*x16, x5 - 29//28*x7, x4*x10 - 7//3*x18]
 [x6*x11 - 129//112*x6, -15//28*x6 + x19, x4*x10 + 43//12*x6, -11//28*x6 + x10, 43//28*x6 + x18, x3*x6 - 9424//1071*x9, -608//153*x9 + x15, -512//153*x9 + x17, x7*x9 - 18944//2601*x9, -19//153*x9 + 1, -475//102*x9 + x11*x12, -76//17

8-element Vector{Vector{MPolyRingElem}}:
 [43//20*t^23*x4 + t^31*x6*x11 + 43//20//t^92*x6 + 509507//414400//t^13*x7*x9 + 2451//560*t^94*x7 - 1419//700//t^26*x9 + 559//100*t^60*x16 + 43//20*t^70*x18, t^23*x4 + 1//t^92*x6 + 11849//20720//t^13*x7*x9 + 57//28*t^94*x7 - 33//35//t^26*x9 + 13//5*t^60*x16 + t^70*x18 + t^91*x19, -341//696*t^23*x4 - 341//696//t^92*x6 - 4128637//14421120//t^13*x7*x9 - 6479//6496*t^94*x7 + 3643//8120//t^26*x9 + 1//t^83*x10 - 4433//3480*t^60*x16 - 11//174*t^70*x18, -473//696*t^23*x4 - 473//696//t^92*x6 - 5653537//14421120//t^13*x7*x9 - 8987//6496*t^94*x7 + 5143//8120//t^26*x9 + t^42*x11 - 6149//3480*t^60*x16 - 77//174*t^70*x18, 1//t^2*x1 + 70227//1108520//t^13*x7*x9 - 1728//3745//t^26*x9 + 432//535*t^60*x16, t^5*x2 + 70227//2217040//t^13*x7*x9 - 864//3745//t^26*x9 + 216//535*t^60*x16, 1//t^98*x3 + 33813//1108520//t^13*x7*x9 - 832//3745//t^26*x9 + 208//535*t^60*x16, -17//1295//t^13*x7*x9 - 1//35//t^26*x9 + 1//t^19, -255//518//t^13*x7*x9 - 15//14//t^26*x9 + t^5*x11*x