In [1]:
include("../src/main.jl");

## Construction of the system

In [2]:
# Define ring of parameters
A, (k1, k2, k3, k4, k5, k6, k7, k8, k9, k10, k11, k12, k13, k14, k15, k16, k17, k18, k19, k20, k21, k22, k23, k24, k25, k26, k27, k28, k29, k30, k31, c1, c2, c3, c4, c5) =
    polynomial_ring(QQ, ["k1", "k2", "k3", "k4", "k5", "k6", "k7", "k8", "k9", "k10", "k11", "k12", "k13", "k14", "k15", "k16", "k17", "k18", "k19", "k20", "k21", "k22", "k23", "k24", "k25", "k26", "k27", "k28", "k29", "k30", "k31", "c1", "c2", "c3", "c4", "c5"]);

# Define ring of parameterized polynomials
B, (x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14, x15, x16, x17, x18, x19) = polynomial_ring(A, ["x1", "x2", "x3", "x4", "x5", "x6", "x7", "x8", "x9", "x10", "x11", "x12", "x13", "x14", "x15", "x16", "x17", "x18", "x19"]);

# Define the square(!) system of steady state equations and conservation laws
steadyStateEqs = [
    -k1 * x1 + k2 * x2, # x1
    k1 * x1 - (k2 + k26) * x2 + k27 * x3 - k3 * x2 * x4 + (k4 + k5) * x14, # x2
    k26 * x2 - k27 * x3 - k14 * x3 * x6 + (k15 + k16) * x15, # x3
    -k3 * x2 * x4 - k9 * x4 * x10 + k4 * x14 + k8 * x16 + (k10 + k11) * x18, # x4
    -k28 * x5 + k29 * x7 - k6 * x5 * x8 + k5 * x14 + k7 * x16, # x5
    -k14 * x3 * x6 - k20 * x6 * x11 + k15 * x15 + k19 * x17 + (k21 + k22) * x19, # x6
    k28 * x5 - k29 * x7 - k17 * x7 * x9 + k16 * x15 + k18 * x17, # x7
    -k6 * x5 * x8 + (k7 + k8) * x16, # x8
    -k17 * x7 * x9 + (k18 + k19) * x17, # x9
    k12 - (k13 + k30) * x10 - k9 * x4 * x10 + k31 * x11 + k10 * x18, # x10
    -k23 * x11 + k30 * x10 - k31 * x11 - k20 * x6 * x11 - k24 * x11 * x12 + k25 * x13 + k21 * x19, # x11
    -k24 * x11 * x12 + k25 * x13, # x12
    -k24 * x11 * x12 + k25 * x13, # x13
    k3 * x2 * x4 - (k4 + k5) * x14, # x14
    k14 * x3 * x6 - (k15 + k16) * x15, # x15
    -k6 * x5 * x8 + (k7 + k8) * x16, # x16
    -k17 * x7 * x9 + (k18 + k19) * x17, # x17
    k9 * x4 * x10 - (k10 + k11) * x18, # x18
    k20 * x6 * x11 - (k21 + k22) * x19]; # x19

conservationLaws = [
    (x1 + x2 + x3 + x14 + x15) - c1,
    (x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19) - c2,
    (x8 + x16) - c3,
    (x9 + x17) - c4,
    (x12 + x13) - c5];

system = vcat([steadyStateEq for (i, steadyStateEq) in enumerate(steadyStateEqs) if i ∉ [3, 4, 8, 9, 12]],
    conservationLaws)


19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -k1*x1 + k2*x2
 k1*x1 - k3*x2*x4 + (-k2 - k26)*x2 + k27*x3 + (k4 + k5)*x14
 -k6*x5*x8 - k28*x5 + k29*x7 + k5*x14 + k7*x16
 -k14*x3*x6 - k20*x6*x11 + k15*x15 + k19*x17 + (k21 + k22)*x19
 k28*x5 - k17*x7*x9 - k29*x7 + k16*x15 + k18*x17
 -k9*x4*x10 + (-k13 - k30)*x10 + k31*x11 + k10*x18 + k12
 -k20*x6*x11 + k30*x10 - k24*x11*x12 + (-k23 - k31)*x11 + k25*x13 + k21*x19
 -k24*x11*x12 + k25*x13
 k3*x2*x4 + (-k4 - k5)*x14
 k14*x3*x6 + (-k15 - k16)*x15
 -k6*x5*x8 + (k7 + k8)*x16
 -k17*x7*x9 + (k18 + k19)*x17
 k9*x4*x10 + (-k10 - k11)*x18
 k20*x6*x11 + (-k21 - k22)*x19
 x1 + x2 + x3 + x14 + x15 - c1
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 - c2
 x8 + x16 - c3
 x9 + x17 - c4
 x12 + x13 - c5

In [3]:
# Make a choice of parameters
number_of_parameters = ngens(coefficient_ring(parent(first(system))))
target_parameters = collect(1:number_of_parameters)
target_system = specialize(system, target_parameters)

19-element Vector{QQMPolyRingElem}:
 -x1 + 2*x2
 x1 - 3*x2*x4 - 28*x2 + 27*x3 + 9*x14
 -6*x5*x8 - 28*x5 + 29*x7 + 5*x14 + 7*x16
 -14*x3*x6 - 20*x6*x11 + 15*x15 + 19*x17 + 43*x19
 28*x5 - 17*x7*x9 - 29*x7 + 16*x15 + 18*x17
 -9*x4*x10 - 43*x10 + 31*x11 + 10*x18 + 12
 -20*x6*x11 + 30*x10 - 24*x11*x12 - 54*x11 + 25*x13 + 21*x19
 -24*x11*x12 + 25*x13
 3*x2*x4 - 9*x14
 14*x3*x6 - 31*x15
 -6*x5*x8 + 15*x16
 -17*x7*x9 + 37*x17
 9*x4*x10 - 21*x18
 20*x6*x11 - 43*x19
 x1 + x2 + x3 + x14 + x15 - 32
 x4 + x5 + x6 + x7 + x14 + x15 + x16 + x17 + x18 + x19 - 33
 x8 + x16 - 34
 x9 + x17 - 35
 x12 + x13 - 36

## Embedding in vertical family

In [4]:
F, target_parameters = vertical_embedding(target_system)

(AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}[-a[1]*x1 + 2*a[2]*x2, a[1]*x1 - 3*a[3]*x2*x4 - 28*a[2]*x2 + 27*a[4]*x3 + 9*a[5]*x14, -6*a[6]*x5*x8 - 28*a[7]*x5 + 29*a[8]*x7 + 5*a[5]*x14 + 7*a[9]*x16, -14*a[10]*x3*x6 - 20*a[11]*x6*x11 + 15*a[12]*x15 + 19*a[13]*x17 + 43*a[14]*x19, 28*a[7]*x5 - 17*a[15]*x7*x9 - 29*a[8]*x7 + 16*a[12]*x15 + 18*a[13]*x17, -9*a[16]*x4*x10 - 43*a[17]*x10 + 31*a[18]*x11 + 10*a[19]*x18 + 12*a[20], -20*a[11]*x6*x11 + 30*a[17]*x10 - 24*a[21]*x11*x12 - 54*a[18]*x11 + 25*a[22]*x13 + 21*a[14]*x19, -24*a[21]*x11*x12 + 25*a[22]*x13, 3*a[3]*x2*x4 - 9*a[5]*x14, 14*a[10]*x3*x6 - 31*a[12]*x15, -6*a[6]*x5*x8 + 15*a[9]*x16, -17*a[15]*x7*x9 + 37*a[13]*x17, 9*a[16]*x4*x10 - 21*a[19]*x18, 20*a[11]*x6*x11 - 43*a[14]*x19, a[1]*x1 + a[2]*x2 + a[4]*x3 + a[5]*x14 + a[12]*x15 - 32*a[20], a[23]*x4 + a[7]*x5 + a[24]*x6 + a[8]*x7 + a[5]*x14 + a[12]*x15 + a[9]*x16 + a[13]*x17 + a[19]*x18 + a[14]*x19 - 33*a[20], a[25]*x8 + a[9]*x16 - 34*a[20], a[26]*x9 + a[13]*x17 - 35*a[20], a[27]*x12 + 

## Pertubation of parameters
This need to be repeated until a transversal intersection is found in next step.

In [5]:
m = length(target_parameters)
Kt, t = rational_function_field(QQ, "t")

v = [-2, 5, -51, -98, -81, 73, 88, 94, 60, 30, 31, -95, 26, 91, -13, -31, -83, 42, 70, -19, 5, 54, 23, -92, 31, -26, -19]
#v = rand(-100:100, m)

perturbed_parameters = (t .^ v) .* target_parameters;

In [6]:
linear_part, binomial_part = modify_vertically(F)
display(linear_part)
display(binomial_part)

19-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -y[1] + 2*y[2]
 y[1] - 28*y[2] - 3*y[3] + 27*y[4] + 9*y[5]
 5*y[5] - 6*y[6] - 28*y[7] + 29*y[8] + 7*y[9]
 -14*y[10] - 20*y[11] + 15*y[12] + 19*y[13] + 43*y[14]
 28*y[7] - 29*y[8] + 16*y[12] + 18*y[13] - 17*y[15]
 -9*y[16] - 43*y[17] + 31*y[18] + 10*y[19] + 12*y[20]
 -20*y[11] + 21*y[14] + 30*y[17] - 54*y[18] - 24*y[21] + 25*y[22]
 -24*y[21] + 25*y[22]
 3*y[3] - 9*y[5]
 14*y[10] - 31*y[12]
 -6*y[6] + 15*y[9]
 37*y[13] - 17*y[15]
 9*y[16] - 21*y[19]
 20*y[11] - 43*y[14]
 y[1] + y[2] + y[4] + y[5] + y[12] - 32*y[20]
 y[5] + y[7] + y[8] + y[9] + y[12] + y[13] + y[14] + y[19] - 33*y[20] + y[23] + y[24]
 y[9] - 34*y[20] + y[25]
 y[13] - 35*y[20] + y[26]
 -36*y[20] + y[22] + y[27]

27-element Vector{AbstractAlgebra.Generic.MPoly{QQMPolyRingElem}}:
 -a[1]*x1 + y[1]
 -a[2]*x2 + y[2]
 -a[3]*x2*x4 + y[3]
 -a[4]*x3 + y[4]
 -a[5]*x14 + y[5]
 -a[6]*x5*x8 + y[6]
 -a[7]*x5 + y[7]
 -a[8]*x7 + y[8]
 -a[9]*x16 + y[9]
 -a[10]*x3*x6 + y[10]
 ⋮
 -a[19]*x18 + y[19]
 y[20] - a[20]
 -a[21]*x11*x12 + y[21]
 -a[22]*x13 + y[22]
 -a[23]*x4 + y[23]
 -a[24]*x6 + y[24]
 -a[25]*x8 + y[25]
 -a[26]*x9 + y[26]
 -a[27]*x12 + y[27]

## Tropicalizations

In [7]:
Kaxy = parent(first(binomial_part));
Ka = coefficient_ring(Kaxy);
K = base_ring(Ka);
Kx, x = polynomial_ring(K, symbols(parent(first(F))));

In [8]:
# Tropicalize the linear part over QQ
linear_part_specialized = specialize(linear_part, K.(ones(Int, ngens(Ka))))
nu_K = tropical_semiring_map(K)
@time TropL = tropical_linear_space(ideal(linear_part_specialized), nu_K)

 45.209539 seconds (715.96 M allocations: 5.592 GiB, 0.14% gc time, 2.73% compilation time)


Min tropical linear space

In [10]:
length(maximal_polyhedra(TropL))

78983

In [13]:
Ktx, x = polynomial_ring(Kt, symbols(Kx))
Ktxy, xy = polynomial_ring(Kt, symbols(Kaxy))

binomial_part_specialized =
    hom(Kaxy, Ktxy, hom(Ka, Kt, perturbed_parameters), gens(Ktxy)).(binomial_part)

# Tropicalize the binomial part over QQt
nu = tropical_semiring_map(Kt, t)
@time TropB = Oscar.tropical_variety_binomial(ideal(binomial_part_specialized), nu)

  0.003311 seconds (15.37 k allocations: 1.822 MiB)


Min tropical variety

## Computation of tropical intersection points

In [14]:
@time pts, mults = tropical_stable_intersection_linear_binomial(TropL, TropB)
projected_pts = [w[1:ngens(Kx)] for w in pts]
grc = sum(mults)

display(projected_pts)
display(mults)
display(grc)

8-element Vector{Vector{QQFieldElem}}:
 [-17, -24, 79, 230, 132, 11, 126, -50, 7, 2, -123, 99, -73, 236, 215, 95, 94, 131, -172]
 [-17, -24, 79, 292, 194, 73, 188, -50, 7, 64, -61, 37, -73, 298, 277, 157, 156, 255, -48]
 [126, 119, 222, -52, -7, -271, -13, -50, 7, -280, -123, 99, -73, 97, 76, -44, -45, -433, -454]
 [-218, -225, -122, 292, -7, -128, -13, -50, -194, 64, 78, 0, 29, 97, -125, -44, -246, 255, -110]
 [91, 84, 187, -52, -42, -236, -48, -50, 42, -245, -123, 99, -73, 62, 76, -79, -45, -398, -419]
 [-235//2, -249//2, -43//2, 56, -42, -55//2, -48, -301//2, 42, 64, -45//2, 0, -143//2, -77//2, 76, -359//2, -45, 19, -110]
 [-156, -163, -60, 56, -42, 11, -48, -189, 42, -75, -200, 176, -73, -77, 76, -218, -45, -120, -249]
 [-17, -24, 79, 56, -308, -128, -314, 216, 308, 64, 78, 0, 29, 62, 76, -79, -45, 19, -110]

8-element Vector{Int64}:
 1
 1
 1
 1
 1
 2
 1
 1

9

 25.449511 seconds (94.74 M allocations: 15.071 GiB, 7.70% gc time, 3.78% compilation time)


## Computation of initials and homotopies for a given point

In [15]:
# Substitution homomorphism Kxy -> Kx with y -> target_parametrs.*monomial_vector
Kxy, xy = polynomial_ring(K, symbols(Kaxy))
target_parameters = (c -> evaluate(c, QQ(1))).(perturbed_parameters)
monomial_vector = -hom(Kaxy, Kx, hom(Ka, K, ones(Int, m)), vcat(gens(Kx), zeros(Kx, m))).(binomial_part)
target_monomial_vector = target_parameters .* monomial_vector
substitute_y_by_monomials = hom(Kxy, Kx, vcat(gens(Kx), target_monomial_vector))

# Substitution homomorphism Kxy -> Ktx with y -> perturbed_parameters.*monomial_vector
perturbed_monomial_vector = perturbed_parameters .* hom(Kx, Ktx, gens(Ktx)).(monomial_vector)
substitute_y_by_perturbed_monomials = hom(Kxy, Ktx, vcat(gens(Ktx), perturbed_monomial_vector));


In [16]:
# Choice of point
w = pts[1]

# Compute the tropical Gröbner basis and initial for the linear part
G_linear = groebner_basis(ideal(linear_part_specialized), nu_K, w)
initials_linear = initial.(G_linear, Ref(nu_K), Ref(w))

# Substitute the y variables by the monomials
initials = substitute_y_by_monomials.(initials_linear)

# Tropical Gröbner basis
G = substitute_y_by_perturbed_monomials.(G_linear)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 43//20*t^23*x4 + t^31*x6*x11 + 43//20//t^92*x6 + 509507//414400//t^13*x7*x9 + 2451//560*t^94*x7 - 1419//700//t^26*x9 + 559//100*t^60*x16 + 43//20*t^70*x18
 t^23*x4 + 1//t^92*x6 + 11849//20720//t^13*x7*x9 + 57//28*t^94*x7 - 33//35//t^26*x9 + 13//5*t^60*x16 + t^70*x18 + t^91*x19
 -341//696*t^23*x4 - 341//696//t^92*x6 - 4128637//14421120//t^13*x7*x9 - 6479//6496*t^94*x7 + 3643//8120//t^26*x9 + 1//t^83*x10 - 4433//3480*t^60*x16 - 11//174*t^70*x18
 -473//696*t^23*x4 - 473//696//t^92*x6 - 5653537//14421120//t^13*x7*x9 - 8987//6496*t^94*x7 + 5143//8120//t^26*x9 + t^42*x11 - 6149//3480*t^60*x16 - 77//174*t^70*x18
 1//t^2*x1 + 70227//1108520//t^13*x7*x9 - 1728//3745//t^26*x9 + 432//535*t^60*x16
 t^5*x2 + 70227//2217040//t^13*x7*x9 - 864//3745//t^26*x9 + 216//535*t^60*x16
 1//t^98*x3 + 33813//1108520//t^13*x7*x9 - 832//3745//t^26*x9 + 208//535*t^60*x16
 -17//1295//t^

In [19]:
# Homotopy in OSCAR format
projected_point = w[1:ngens(Kx)]
H = homotopy_from_tropical_data(G,projected_point)

19-element Vector{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.RationalFunctionFieldElem{QQFieldElem, QQPolyRingElem}}}:
 43//20*t^334*x4 + x6*x11 + 43//20*x6 + 509507//414400*t^201*x7*x9 + 2451//560*t^301*x7 - 1419//700*t^62*x9 + 559//100*t^236*x16 + 43//20*t^282*x18
 t^334*x4 + x6 + 11849//20720*t^201*x7*x9 + 57//28*t^301*x7 - 33//35*t^62*x9 + 13//5*t^236*x16 + t^282*x18 + x19
 -341//696*t^334*x4 - 341//696*x6 - 4128637//14421120*t^201*x7*x9 - 6479//6496*t^301*x7 + 3643//8120*t^62*x9 + x10 - 4433//3480*t^236*x16 - 11//174*t^282*x18
 -473//696*t^334*x4 - 473//696*x6 - 5653537//14421120*t^201*x7*x9 - 8987//6496*t^301*x7 + 5143//8120*t^62*x9 + x11 - 6149//3480*t^236*x16 - 77//174*t^282*x18
 x1 + 70227//1108520*t^139*x7*x9 - 1728//3745*x9 + 432//535*t^174*x16
 x2 + 70227//2217040*t^139*x7*x9 - 864//3745*x9 + 216//535*t^174*x16
 x3 + 33813//1108520*t^139*x7*x9 - 832//3745*x9 + 208//535*t^174*x16
 -17//1295*t^139*x7*x9 - 1//35*x9 + 1
 -255//518*t^139*x7*x9 - 15//14*x9 + x11*x12 + 

## Solve start system and trace along homotopy

In [20]:
# Solve start system
S_HC = HC_system_from_Oscar_system(initials)
start_solutions = solve_binomial_system(S_HC)

1-element Vector{Vector{ComplexF64}}:
 [16.14953271028037 + 0.0im, 8.074766355140184 + 0.0im, 7.7757009345794375 + 0.0im, -4.871175051999501 + 0.0im, -0.6025367711379261 + 0.0im, -3.1636363636363636 + 0.0im, -0.5817596410986873 + 0.0im, 33.99999999999999 + 0.0im, 34.99999999999999 + 0.0im, -1.55 + 0.0im, -2.15 + 0.0im, -17.441860465116275 + 0.0im, 35.99999999999999 + 0.0im, -13.111200139961271 + 0.0im, -11.109447200372733 + 0.0im, -8.194500087475793 + 0.0im, -9.355323958208619 + 0.0im, 3.2358519988282395 + 0.0im, 3.1636363636363636 + 0.0im]

In [21]:
# Homotopy in HC format
H_HC = export_homotopy_from_oscar_to_HC(H)
trace_solutions_along_homotopy(H_HC, start_solutions)

1-element Vector{Vector{ComplexF64}}:
 [31.828140736431813 + 0.0im, 15.914070368215906 - 2.8698592549372254e-42im, 15.32466035457828 - 1.7219155529623352e-41im, -3.1211155334604483 - 3.587324068671532e-42im, -0.5833341167614661 - 5.3809861030072976e-43im, -2.096620422889337 - 2.152394441202919e-42im, -0.5632191472179672 + 0.0im, 44.34784421392111 + 0.0im, 47.21921744585451 - 5.739718509874451e-42im, -41.5819997874999 + 0.0im, -38.328887079339516 + 0.0im, -1.0057065017175382 + 0.0im, 37.00570650171753 - 4.304788882405838e-42im, -16.55655074227377 - 5.739718509874451e-42im, -14.510320716952233 - 5.739718509874451e-42im, -10.347844213921105 - 5.739718509874451e-42im, -12.219217445854513 - 2.2958874039497803e-41im, 55.62095376390643 + 2.2958874039497803e-41im, 37.3772685754244 - 1.7219155529623352e-41im]

## Functions that put the above together

In [22]:
# Computation of tropical intersection data
grc, projected_pts, initial_systems, tropical_groebner_bases, perturbed_parameters =
    tropical_root_count_with_homotopy_data_vertical(F, perturbed_parameters=perturbed_parameters, verbose=true)

display(grc)
display(projected_pts)
display(initial_systems)
display(tropical_groebner_bases)

Time spent tropicalizing the linear part: 59.560788458
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.002771458
Time spent on stable intersection: 31.226437667


9

8-element Vector{Vector{QQFieldElem}}:
 [-17, -24, 79, 230, 132, 11, 126, -50, 7, 2, -123, 99, -73, 236, 215, 95, 94, 131, -172]
 [-17, -24, 79, 292, 194, 73, 188, -50, 7, 64, -61, 37, -73, 298, 277, 157, 156, 255, -48]
 [126, 119, 222, -52, -7, -271, -13, -50, 7, -280, -123, 99, -73, 97, 76, -44, -45, -433, -454]
 [-218, -225, -122, 292, -7, -128, -13, -50, -194, 64, 78, 0, 29, 97, -125, -44, -246, 255, -110]
 [91, 84, 187, -52, -42, -236, -48, -50, 42, -245, -123, 99, -73, 62, 76, -79, -45, -398, -419]
 [-235//2, -249//2, -43//2, 56, -42, -55//2, -48, -301//2, 42, 64, -45//2, 0, -143//2, -77//2, 76, -359//2, -45, 19, -110]
 [-156, -163, -60, 56, -42, 11, -48, -189, 42, -75, -200, 176, -73, -77, 76, -218, -45, -120, -249]
 [-17, -24, 79, 56, -308, -128, -314, 216, 308, 64, 78, 0, 29, 62, 76, -79, -45, 19, -110]

8-element Vector{Vector{QQMPolyRingElem}}:
 [x6*x11 + 43//20*x6, x6 + x19, -341//696*x6 + x10, -473//696*x6 + x11, x1 - 1728//3745*x9, x2 - 864//3745*x9, x3 - 832//3745*x9, -1//35*x9 + 1, -15//14*x9 + x11*x12, -36//35*x9 + x13, x8 - 34//35*x9, x3*x6 - 10013//8288*x7*x9, -323//592*x7*x9 + x15, -17//37*x7*x9 + x17, x2*x4 - 24//5*x16, x14 - 8//5*x16, x5*x8 - 5//2*x16, x4*x10 - 7//3*x18, x5 - 29//28*x7]
 [x1 - 1728//3745*x9, x2 - 864//3745*x9, x3 - 832//3745*x9, -27//2030*x9 + x10, -3//406*x9 + x11, -1//35*x9 + 1, -15//14*x9 + x11*x12, -36//35*x9 + x13, x6 - 33//35*x9, x8 - 34//35*x9, x6*x11 - 43//20*x19, x3*x6 - 10013//8288*x7*x9, -323//592*x7*x9 + x15, -17//37*x7*x9 + x17, x2*x4 - 24//5*x16, x14 - 8//5*x16, x5*x8 - 5//2*x16, x5 - 29//28*x7, x4*x10 - 7//3*x18]
 [x6*x11 - 129//112*x6, -15//28*x6 + x19, x4*x10 + 43//12*x6, -11//28*x6 + x10, 43//28*x6 + x18, x3*x6 - 9424//1071*x9, -608//153*x9 + x15, -512//153*x9 + x17, x7*x9 - 18944//2601*x9, -19//153*x9 + 1, -475//102*x9 + x11*x12, -76//17

8-element Vector{Vector{MPolyRingElem}}:
 [43//20*t^23*x4 + t^31*x6*x11 + 43//20//t^92*x6 + 509507//414400//t^13*x7*x9 + 2451//560*t^94*x7 - 1419//700//t^26*x9 + 559//100*t^60*x16 + 43//20*t^70*x18, t^23*x4 + 1//t^92*x6 + 11849//20720//t^13*x7*x9 + 57//28*t^94*x7 - 33//35//t^26*x9 + 13//5*t^60*x16 + t^70*x18 + t^91*x19, -341//696*t^23*x4 - 341//696//t^92*x6 - 4128637//14421120//t^13*x7*x9 - 6479//6496*t^94*x7 + 3643//8120//t^26*x9 + 1//t^83*x10 - 4433//3480*t^60*x16 - 11//174*t^70*x18, -473//696*t^23*x4 - 473//696//t^92*x6 - 5653537//14421120//t^13*x7*x9 - 8987//6496*t^94*x7 + 5143//8120//t^26*x9 + t^42*x11 - 6149//3480*t^60*x16 - 77//174*t^70*x18, 1//t^2*x1 + 70227//1108520//t^13*x7*x9 - 1728//3745//t^26*x9 + 432//535*t^60*x16, t^5*x2 + 70227//2217040//t^13*x7*x9 - 864//3745//t^26*x9 + 216//535*t^60*x16, 1//t^98*x3 + 33813//1108520//t^13*x7*x9 - 832//3745//t^26*x9 + 208//535*t^60*x16, -17//1295//t^13*x7*x9 - 1//35//t^26*x9 + 1//t^19, -255//518//t^13*x7*x9 - 15//14//t^26*x9 + t^5*x11*x

## Function that solves the full system

In [24]:
# Function that puts all of the above together
sols = tropical_solve(F, target_parameters; type_of_system=:vertical, verbose=true)

Time spent tropicalizing the linear part: 57.967633542
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.002880458
ErrorException("random direction not generic")
Time spent tropicalizing the linear part: 59.291171292
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.003115542
ErrorException("random direction not generic")
Time spent tropicalizing the linear part: 59.073740583
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.007224916
ErrorException("random direction not generic")
Time spent tropicalizing the linear part: 59.47139925
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.002217334
ErrorException("random direction not generic")
Time spent tropicalizing the linear part: 59.734825667
Number of maximal polyhedra: 78983
Time spent tropicalizing the binomial part: 0.002708875
Time spent on stable intersection: 27.9323225
Time spent computing start solutions:

9-element Vector{Vector{ComplexF64}}:
 [5.9661095164262745 + 7.006492321624085e-45im, 2.9830547582131373 + 3.1529215447308384e-45im, 2.8725712486496873 + 3.5032461608120427e-45im, -917.6663863798312 + 9.41672568026277e-43im, -2.3593418270534787 + 6.842277657836021e-48im, 718.9303222573541 - 8.96831017167883e-43im, -2.2779852123274966 - 8.552847072295026e-48im, 604.3018917380439 + 1.401298464324817e-44im, -750.3989821116473 - 2.977759236690236e-45im, -0.002801599784992376 - 4.7895943604852146e-48im, -1.1341749582166306e-5 - 5.131708243377016e-49im, 36.00039197513342 + 3.28429327576129e-45im, -0.000391975133416121 - 1.0947644252537633e-47im, -912.4830267808703 - 2.1019476964872256e-44im, 932.6612912575812 + 7.269235783684989e-45im, -570.3018917380439 - 1.1210387714598537e-44im, 785.3989821116473 + 6.218261935441376e-45im, 1.101828836047057 + 2.7369110631344083e-47im, -0.003792524503287923 - 6.842277657836021e-48im]
 [-13.664827272550518 - 9.780112998841432e-36im, -6.832413636275259 - 2.3

In [25]:
# Certification
F_target_HC = HC_system_from_Oscar_system(target_system)
HC.certify(F_target_HC, sols)

Certifying 9 solutions...  22%|█████▌                   |  ETA: 0:00:05


Certifying 9 solutions... 100%|█████████████████████████| Time: 0:00:01
  # processed:         9
  # certified (real):  9 (7)
  # distinct (real):   7 (6)


CertificationResult
• 9 solution candidates given
• 9 certified solution intervals (7 real, 2 complex)
• 7 distinct certified solution intervals (6 real, 1 complex)

Things to do:
* Check why certification fails
* Transversality check